apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: boredapi-service-entry
spec:
  hosts:
  - www.boredapi.com
  ports:
  - number: 443
    name: tls
    protocol: TLS
  resolution: DNS
  location: MESH_EXTERNAL
